services:
  redis:
    image: redis:7-alpine
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_container
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${SPRING_RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${SPRING_RABBITMQ_PASSWORD}
    mem_limit: 512m
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  auth_service:
    build:
      context: .
      dockerfile: auth/Dockerfile
    container_name: auth_service
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8001:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/twitch_monitor
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_RABBITMQ_HOST: ${SPRING_RABBITMQ_HOST}
      SPRING_RABBITMQ_PORT: ${SPRING_RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${SPRING_RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${SPRING_RABBITMQ_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - rabbitmq
    volumes:
      - ./logs:/app/logs

  twitch_service:
    build:
      context: .
      dockerfile: twitchService/Dockerfile
    container_name: twitch_service
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8002:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/twitch_monitor
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT}
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs

  test_api:
    build:
      context: .
      dockerfile: testApi/Dockerfile
    container_name: test_api
    restart: always
    ports:
      - "8003:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_RABBITMQ_HOST: ${SPRING_RABBITMQ_HOST}
      SPRING_RABBITMQ_PORT: ${SPRING_RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${SPRING_RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${SPRING_RABBITMQ_PASSWORD}
    depends_on:
      - rabbitmq

  newyear_service:
    build:
      context: .
      dockerfile: newYearService/Dockerfile
    container_name: newyear_service
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8004:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/twitch_monitor
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
      - rabbitmq

volumes:
  redis_data:
  rabbitmq_data:
