spring:
  application:
    name: auth

  datasource:
    url: jdbc:postgresql://localhost:5433/twitch_monitor
    username: postgres
    password: 7557

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    servlet:
      path: /api/v1/auth

# Настройки обработки JSON
  jackson:
    deserialization:
      fail-on-unknown-properties: true  # Ожидает ошибку, если встречаются неизвестные свойства в JSON

jwt:
  secret: AHHAHAHAHAHHAHJSDBGJHKSDABG232234FSHKFJHS  #
  expiration: 3600000

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    cersei.twitchservice: DEBUG
  file:
    name: logs/auth.log

