spring:
  application:
    name: newYearService

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/twitch_monitor
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    servlet:
      path: /api/v1/newyear

server:
  port: ${SERVER_PORT:8000}

jwt:
  secret: ${JWT_SECRET:change_me}

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    cersei.newyearservice: DEBUG
  file:
    name: logs/newyearservice.log

