spring:
  application:
    name: testApi

  mvc:
    servlet:
      path: /api/v1/test

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

server:
  port: ${SERVER_PORT:8000}

jwt:
  secret: ${JWT_SECRET:AHHAHAHAHAHHAHJSDBGJHKSDABG232234FSHKFJHS}
